// Every user-invokable command: shown in the command palette, bindable to shortcuts, used by menus.
// "Mod" = Ctrl on Windows, Cmd on macOS.

export interface CommandDef {
  id: string;
  label: string;
  group: string;
  keys?: string;
}

export const COMMANDS: CommandDef[] = [
  // Navigation
  { id: 'nav.mail', label: 'Zu E-Mail wechseln', group: 'Navigation', keys: 'Mod+1' },
  { id: 'nav.calendar', label: 'Zu Kalender wechseln', group: 'Navigation', keys: 'Mod+2' },
  { id: 'nav.contacts', label: 'Zu Kontakten wechseln', group: 'Navigation', keys: 'Mod+3' },
  { id: 'nav.tasks', label: 'Zu Aufgaben wechseln', group: 'Navigation', keys: 'Mod+4' },
  { id: 'nav.notes', label: 'Zu Notizen wechseln', group: 'Navigation', keys: 'Mod+5' },
  { id: 'nav.settings', label: 'Einstellungen öffnen', group: 'Navigation', keys: 'Mod+,' },
  { id: 'nav.palette', label: 'Befehlspalette', group: 'Navigation', keys: 'Mod+K' },
  { id: 'nav.search', label: 'Suchen', group: 'Navigation', keys: 'Mod+E' },
  { id: 'nav.inbox', label: 'Posteingang (alle Konten)', group: 'Navigation', keys: 'Mod+Shift+I' },
  { id: 'nav.goToFolder', label: 'Gehe zu Ordner …', group: 'Navigation', keys: 'Mod+Y' },
  { id: 'nav.shortcuts', label: 'Tastenkombinationen anzeigen', group: 'Navigation', keys: 'Mod+/' },
  // Mail
  { id: 'mail.new', label: 'Neue E-Mail', group: 'E-Mail', keys: 'Mod+N' },
  { id: 'mail.reply', label: 'Antworten', group: 'E-Mail', keys: 'Mod+R' },
  { id: 'mail.replyAll', label: 'Allen antworten', group: 'E-Mail', keys: 'Mod+Shift+R' },
  { id: 'mail.forward', label: 'Weiterleiten', group: 'E-Mail', keys: 'Mod+F' },
  { id: 'mail.delete', label: 'Löschen', group: 'E-Mail', keys: 'Delete' },
  { id: 'mail.deletePermanent', label: 'Endgültig löschen', group: 'E-Mail', keys: 'Shift+Delete' },
  { id: 'mail.archive', label: 'Archivieren', group: 'E-Mail', keys: 'Backspace' },
  { id: 'mail.move', label: 'Verschieben nach …', group: 'E-Mail', keys: 'Mod+Shift+V' },
  { id: 'mail.copy', label: 'Kopieren nach …', group: 'E-Mail' },
  { id: 'mail.markRead', label: 'Als gelesen markieren', group: 'E-Mail', keys: 'Mod+Q' },
  { id: 'mail.markUnread', label: 'Als ungelesen markieren', group: 'E-Mail', keys: 'Mod+U' },
  { id: 'mail.toggleFlag', label: 'Kennzeichnung umschalten', group: 'E-Mail', keys: 'Insert' },
  { id: 'mail.pin', label: 'Anheften / Lösen', group: 'E-Mail' },
  { id: 'mail.snooze', label: 'Zurückstellen …', group: 'E-Mail' },
  { id: 'mail.junk', label: 'Als Junk markieren', group: 'E-Mail', keys: 'Mod+J' },
  { id: 'mail.notJunk', label: 'Kein Junk', group: 'E-Mail' },
  { id: 'mail.block', label: 'Absender blockieren', group: 'E-Mail' },
  { id: 'mail.category', label: 'Kategorisieren …', group: 'E-Mail' },
  { id: 'mail.toTask', label: 'Als Aufgabe hinzufügen', group: 'E-Mail', keys: 'Mod+Shift+T' },
  { id: 'mail.toEvent', label: 'Als Termin planen', group: 'E-Mail' },
  { id: 'mail.print', label: 'Drucken', group: 'E-Mail', keys: 'Mod+P' },
  { id: 'mail.saveAs', label: 'Als .eml speichern', group: 'E-Mail', keys: 'Mod+S' },
  { id: 'mail.source', label: 'Quelltext anzeigen', group: 'E-Mail', keys: 'Mod+Alt+U' },
  { id: 'mail.importEml', label: '.eml-Datei importieren', group: 'E-Mail' },
  { id: 'mail.unsubscribe', label: 'Abo kündigen', group: 'E-Mail' },
  { id: 'mail.selectAll', label: 'Alle auswählen', group: 'E-Mail', keys: 'Mod+A' },
  { id: 'mail.next', label: 'Nächste Nachricht', group: 'E-Mail', keys: 'ArrowDown' },
  { id: 'mail.prev', label: 'Vorherige Nachricht', group: 'E-Mail', keys: 'ArrowUp' },
  { id: 'mail.open', label: 'In eigenem Fenster öffnen', group: 'E-Mail', keys: 'Enter' },
  { id: 'mail.sync', label: 'Senden/Empfangen', group: 'E-Mail', keys: 'F9' },
  { id: 'mail.markFolderRead', label: 'Ordner als gelesen markieren', group: 'E-Mail' },
  { id: 'mail.emptyTrash', label: 'Gelöschte Elemente leeren', group: 'E-Mail' },
  { id: 'mail.newFolder', label: 'Neuer Ordner', group: 'E-Mail', keys: 'Mod+Shift+E' },
  { id: 'mail.filterUnread', label: 'Filter: Ungelesen', group: 'E-Mail' },
  { id: 'mail.filterFlagged', label: 'Filter: Gekennzeichnet', group: 'E-Mail' },
  { id: 'mail.filterAll', label: 'Filter: Alle', group: 'E-Mail' },
  { id: 'mail.outbox', label: 'Postausgang anzeigen', group: 'E-Mail' },
  { id: 'mail.runRules', label: 'Regeln jetzt ausführen', group: 'E-Mail' },
  { id: 'mail.newRule', label: 'Regel aus Nachricht erstellen', group: 'E-Mail' },
  // Compose
  { id: 'compose.send', label: 'Senden', group: 'Verfassen', keys: 'Mod+Enter' },
  { id: 'compose.save', label: 'Entwurf speichern', group: 'Verfassen', keys: 'Mod+S' },
  { id: 'compose.attach', label: 'Datei anfügen', group: 'Verfassen', keys: 'Mod+Shift+A' },
  { id: 'compose.discard', label: 'Verwerfen', group: 'Verfassen' },
  // Calendar
  { id: 'calendar.newEvent', label: 'Neuer Termin', group: 'Kalender', keys: 'Mod+Shift+A' },
  { id: 'calendar.today', label: 'Heute', group: 'Kalender', keys: 'Alt+Home' },
  { id: 'calendar.next', label: 'Nächster Zeitraum', group: 'Kalender', keys: 'Alt+ArrowRight' },
  { id: 'calendar.prev', label: 'Vorheriger Zeitraum', group: 'Kalender', keys: 'Alt+ArrowLeft' },
  { id: 'calendar.viewDay', label: 'Tagesansicht', group: 'Kalender', keys: 'Mod+Alt+1' },
  { id: 'calendar.viewWorkweek', label: 'Arbeitswoche', group: 'Kalender', keys: 'Mod+Alt+2' },
  { id: 'calendar.viewWeek', label: 'Wochenansicht', group: 'Kalender', keys: 'Mod+Alt+3' },
  { id: 'calendar.viewMonth', label: 'Monatsansicht', group: 'Kalender', keys: 'Mod+Alt+4' },
  { id: 'calendar.viewAgenda', label: 'Agenda', group: 'Kalender', keys: 'Mod+Alt+5' },
  { id: 'calendar.import', label: 'Kalender importieren (.ics)', group: 'Kalender' },
  { id: 'calendar.export', label: 'Kalender exportieren (.ics)', group: 'Kalender' },
  { id: 'calendar.new', label: 'Neuer Kalender', group: 'Kalender' },
  { id: 'calendar.subscribe', label: 'Internetkalender abonnieren', group: 'Kalender' },
  // Contacts
  { id: 'contacts.new', label: 'Neuer Kontakt', group: 'Kontakte', keys: 'Mod+Shift+C' },
  { id: 'contacts.importVcf', label: 'Kontakte importieren (.vcf)', group: 'Kontakte' },
  { id: 'contacts.importCsv', label: 'Kontakte importieren (.csv)', group: 'Kontakte' },
  { id: 'contacts.exportVcf', label: 'Kontakte exportieren (.vcf)', group: 'Kontakte' },
  // Tasks
  { id: 'tasks.new', label: 'Neue Aufgabe', group: 'Aufgaben', keys: 'Mod+Shift+K' },
  { id: 'notes.new', label: 'Neue Notiz', group: 'Notizen', keys: 'Mod+Shift+N' },
  // View
  { id: 'view.readingRight', label: 'Lesebereich rechts', group: 'Ansicht' },
  { id: 'view.readingBottom', label: 'Lesebereich unten', group: 'Ansicht' },
  { id: 'view.readingOff', label: 'Lesebereich aus', group: 'Ansicht' },
  { id: 'view.toggleFolders', label: 'Ordnerbereich ein/aus', group: 'Ansicht', keys: 'Mod+Shift+F' },
  { id: 'view.toggleConversations', label: 'Unterhaltungsansicht ein/aus', group: 'Ansicht' },
  { id: 'view.themeLight', label: 'Design: Hell', group: 'Ansicht' },
  { id: 'view.themeDark', label: 'Design: Dunkel', group: 'Ansicht' },
  { id: 'view.themeSystem', label: 'Design: System', group: 'Ansicht' },
  { id: 'view.densityCompact', label: 'Dichte: Kompakt', group: 'Ansicht' },
  { id: 'view.densityComfortable', label: 'Dichte: Normal', group: 'Ansicht' },
  { id: 'view.zoomIn', label: 'Schrift vergrößern', group: 'Ansicht', keys: 'Mod+=' },
  { id: 'view.zoomOut', label: 'Schrift verkleinern', group: 'Ansicht', keys: 'Mod+-' },
  { id: 'view.zoomReset', label: 'Schriftgröße zurücksetzen', group: 'Ansicht', keys: 'Mod+0' },
  // Accounts & app
  { id: 'account.add', label: 'Konto hinzufügen', group: 'Konten' },
  { id: 'account.addDemo', label: 'Demo-Konto hinzufügen', group: 'Konten' },
  { id: 'settings.accounts', label: 'Konten verwalten', group: 'Einstellungen' },
  { id: 'settings.rules', label: 'Regeln verwalten', group: 'Einstellungen' },
  { id: 'settings.signatures', label: 'Signaturen verwalten', group: 'Einstellungen' },
  { id: 'settings.categories', label: 'Kategorien verwalten', group: 'Einstellungen' },
  { id: 'settings.quickSteps', label: 'QuickSteps verwalten', group: 'Einstellungen' },
  { id: 'settings.templates', label: 'Vorlagen verwalten', group: 'Einstellungen' },
  { id: 'settings.outOfOffice', label: 'Automatische Antworten', group: 'Einstellungen' },
  { id: 'settings.shortcuts', label: 'Tastenkombinationen anpassen', group: 'Einstellungen' },
  { id: 'settings.export', label: 'Einstellungen & Daten exportieren', group: 'Einstellungen' },
  { id: 'settings.import', label: 'Einstellungen & Daten importieren', group: 'Einstellungen' },
  { id: 'app.dataDir', label: 'Datenordner öffnen', group: 'App' },
  { id: 'app.clearCache', label: 'Nachrichten-Cache leeren', group: 'App' },
  { id: 'app.newWindow', label: 'Neues Fenster', group: 'App', keys: 'Mod+Shift+W' },
  { id: 'app.reload', label: 'Oberfläche neu laden', group: 'App' },
  { id: 'app.quit', label: 'Beenden', group: 'App' }
];

export const COMMAND_BY_ID = new Map(COMMANDS.map((c) => [c.id, c]));
